ignore and warn adding duplicate component, #993
AlmasB/FXGL pull request #1033
Opened 2021-04-29 10:33 UTC by Zhack47

2021-04-29 13:16 UTC, AlmasB commented
Well spotted, thanks.

@adambocco please can you review when you get a chance

2021-05-15 18:09 UTC, adambocco requested changes
The change looks good as long as it seems like the best idea to warn and ignore instead of throwing an error for duplicate components. I could see a case for either side but would rather the ignore as well.

2021-05-15 18:09 UTC, adambocco commented on fxgl-entity/src/test/kotlin/com/almasb/fxgl/entity/EntityTest.kt
> +        val exception = assertDoesNotThrow {
The test name doesn't match the test performed in this change. Should we just get rid of this test and make one like `Adding duplicate component is ignored` and check if the original component remains on the entity.

2021-05-15 18:09 UTC, adambocco commented on fxgl-entity/src/test/kotlin/com/almasb/fxgl/entity/EntityTest.kt
> +    // Test seems duplicate, see l.51 `Add component fails if same type already exists`
Same here. Maybe change this to create two `TestControl` objects and check if the first one is the added component like:
```
control1 = TestControl()
control2 = TestControl()
entity.addComponent(control1)
entity.addComponent(control2)
assertThat(entity.getComponent(TestControl::class.java),  `is`(control1))
```

2021-05-20 08:58 UTC, fizietechD approved these changes

2021-05-20 08:58 UTC, Fizie92 approved these changes

2021-05-20 09:14 UTC, AlmasB commented on fxgl-entity/src/test/kotlin/com/almasb/fxgl/entity/EntityTest.kt
> +        val exception = assertDoesNotThrow {
Good point, updated.

2021-05-20 09:15 UTC, AlmasB approved these changes
Thanks for the reviews @adambocco @Fizie92 

Thanks for the PR @Zhack47

2021-05-20 09:16 UTC, merged