docs: Add Chinese README file
AlmasB/FXGL pull request #1186
Opened 2022-07-20 16:49 UTC by lhDream

2022-07-20 19:49 UTC, AlmasB reviewed
Thanks a lot @lhDream , this is a great idea!

@chengenzhao as you kindly offered to help with #1172, can you help me review `README_CN` please.

2022-07-20 19:49 UTC, AlmasB commented on README.md
> +## 语言
语言 should be "Language" since this file is the English version

2022-07-20 19:55 UTC, AlmasB commented on README_CN.md
> +如果您想从源代码构建 FXGL 或想贡献，请参阅[贡献指南](https://github.com/lhDream/FXGL/blob/dev/CONTRIBUTING.md)（包括非代码）。FXGL 是完全模块化的，因此新的贡献者不需要了解整个代码库，只需要了解做出贡献的模块即可。贡献将根据[行为准则](https://github.com/lhDream/FXGL/blob/dev/CODE
I think these links (contributing and code of conduct) need to be rerouted to main repo.

2022-07-21 00:14 UTC, chengenzhao requested changes
根据一些语言习惯和上下文环境，做了相应的修改建议
Based on language custom and context, provided some suggestions

2022-07-21 00:14 UTC, chengenzhao commented on README.md
> +## 语言
```suggestion
## Languages
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- 简单干净的API，比其他引擎更高级别
```suggestion
- 简单干净的API，相比起其他引擎API级别更高
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- 实验 3D
```suggestion
- 实验性 3D 特性
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- [将 FXGL 与 IntelliJ 一起使用](https://youtu.be/LhmlFC6KE2Q)
```suggestion
- [与 FXGL 与 IntelliJ 一起使用](https://youtu.be/LhmlFC6KE2Q)
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- [展示预告片](https://youtu.be/fuDQg7W0v4g)
```suggestion
- [预告片展示](https://youtu.be/fuDQg7W0v4g)
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- 在 `itch.io `上发布了[演示](https://fxgl.itch.io/)
```suggestion
- [演示](https://fxgl.itch.io/)在 `itch.io `上发布
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +注意：`0.5.4`用于 Java 8-10 和`11.17`Java 11-16。
```suggestion
注意：`0.5.4` 及 `11.17` 分别适用于 Java 8-10  及 Java 11-16。
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- [Maven](https://github.com/AlmasB/FXGL-MavenGradle)模板项目，如果你使用 Java 和/或 Kotlin (Java 17+)
```suggestion
- [Maven](https://github.com/AlmasB/FXGL-MavenGradle)项目模板，编程语言为 Java 和/或 Kotlin (Java 17+)
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- 如果您使用 Java 和/或 Kotlin (Java 17+)，则为[Gradle模板项目](https://github.com/AlmasB/FXGL-MavenGradle)
```suggestion
- [Gradle项目模板](https://github.com/AlmasB/FXGL-MavenGradle)，编程语言为 Java 和/或 Kotlin (Java 17+)
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +注意：`0.5.4`用于 Java 8-10 和`11.17`Java 11-16。
```suggestion
注意：注意：`0.5.4` 及 `11.17` 分别适用于 Java 8-10  及 Java 11-16。
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +### Uber jar
```suggestion
### 独立完整包含所有依赖的 jar 文件
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +- FHNW 工程/计算机科学学院，瑞士
```suggestion
- 瑞士西北高等专业学院 工程/计算机科学学院
```

2022-07-21 00:14 UTC, chengenzhao commented on README_CN.md
> +### 接触
```suggestion
### 与我们取得联系
```

2022-07-21 07:46 UTC, AlmasB commented
Thank you both.

@chengenzhao let me know if ok to merge.

2022-07-21 08:08 UTC, chengenzhao commented
@lhDream 还有两个修改建议，是遗漏了还是保留原先的翻译？

2022-07-21 08:56 UTC, lhDream commented
@chengenzhao 两个？那应该是漏了一个,等下我瞅一眼。在考虑用原来的还是换成这个 `在IntelliJ中使用FXGL`

2022-07-21 09:11 UTC, chengenzhao commented
> 

我觉得：在IntelliJ中使用FXGL
这个翻译比较好，改好就行了，我先approve一下

2022-07-21 09:11 UTC, chengenzhao approved these changes

2022-07-21 09:16 UTC, lhDream commented
OK

2022-07-21 09:22 UTC, chengenzhao commented
@AlmasB the doc is good to go

2022-07-21 09:48 UTC, merged

2022-07-21 09:50 UTC, AlmasB commented
Great, many thanks!