feat: Support diagonal pathfinding movement
AlmasB/FXGL pull request #1334
Opened 2024-01-19 20:03 UTC by DeathPhoenix22

Hi @AlmasB ,

I've completed the implementation to allow diagonal Pathfinding movement. This implementation is "backward compatible" by setting the parameter Diagonal to "Never" by default. To enable Diagonal movement, simply provide the Diagonal.ALLOWED flag in the constructor on through it's Setter.

I've defaulted the AStarPathfindingSample to Diagonal.ALLOWED.

As requested, I'll do the changes "step by step".
Note: Because I'm doing it "step by step", this means that future PRs will depend on each others.

Possible Upcoming changes (No promises):
- Optimizations -> Reduced memory allocation, Faster calculation, etc
- Include a "No Corner Crossing" option -> This is to prevent "noisy" collisions detection when an Entity walks close to a diagonal wall
- Flexible CellState definition -> Ability to define your own CellStates & allow defining "allowed" states while retrieving the Path. For example, you could wish to have a single state grid that will support Ground vs Water vs Amphibious pathfinding
- Allow AStarGrid (.fromWorld(...)) to be loaded by Entity instead of restricting it by entity types. Currently, only the type of the entity may be used to define if a Cell is walkable or not. Having the Entity directly offers more flexibility.
- 16 Directions Pathfinding -> Tricky, but it would add a noticeable "smoothness" to Entity movements

Let me know if I should adjust it.

2024-01-30 12:06 UTC, AlmasB requested changes
Thanks for this, it looks really good.

Could we separate it into two PRs, it will be easier to review and merge.

1) Introduce the concept of diagonal neighbors.
2) Implement A* support of diagonal movement.

I've left some comments related to (1). Once it is merged, we can start looking at (2).

2024-01-30 12:06 UTC, AlmasB commented on fxgl-core/src/main/java/com/almasb/fxgl/core/collection/grid/Grid.java
> +    private Diagonal diagonal;
The grid in itself is just a data structure. I think the fact that diagonal movement is supported or not could be extracted out of this and dictated by higher level code/system.

2024-01-30 12:06 UTC, AlmasB commented on fxgl-core/src/main/java/com/almasb/fxgl/core/collection/grid/Grid.java
> +    public final Optional<T> getUpRight(Cell cell) {
These are useful convenience methods for the first of the two PRs.

2024-01-30 12:06 UTC, AlmasB commented on fxgl-core/src/main/java/com/almasb/fxgl/core/collection/grid/Grid.java
> +        // Include "Corner" neighbors only if diagonal movement is allowed
This should go into a new method `getNeighbors` that allows us to provide info on how to extract the neighbors.

```
getNeighbors(x, y, NeighborFilteringOption.FOUR_DIRECTIONS)

NeighborFilteringOption.EIGHT_DIRECTIONS
```
If we need more in the future, we can modify as appropriate.

2024-01-31 15:26 UTC, DeathPhoenix22 commented
> Thanks for this, it looks really good.
> 
> Could we separate it into two PRs, it will be easier to review and merge.
> 
> 1. Introduce the concept of diagonal neighbors.
> 2. Implement A* support of diagonal movement.
> 
> I've left some comments related to (1). Once it is merged, we can start looking at (2).

Hi @AlmasB , from a functional perspective, both PRs will be tightly coupled and useless without the other. 
Failing to merge the second PR will render the 1st PR dead code. 

I'll comply, but I don't recommend segmenting this PR.
Have a nice day :)

2024-01-31 15:27 UTC, closed without merging