Added positionOriginZ to TransformComponent
AlmasB/FXGL pull request #929
Opened 2021-01-07 16:42 UTC by VasilisAndritsoudis

From class ViewComponent:
    Changed:
    `viewRoot.translateZProperty().bind(entity.transformComponent.zProperty())`
    To:
    `viewRoot.translateZProperty().bind(entity.yProperty().subtract(entity.transformComponent.positionOriginZProperty()))`

From class TransformComponent:
  And added the necessary variable and function in order to work correctly:
  `private val propPositionOriginZ = SimpleDoubleProperty(0.0)`
  `fun positionOriginZProperty() = propPositionOriginZ`

Run some basic tests using the supplied 3D examples under fxgl-samples / ... / sandbox/test3d and everything seemed to be fine.

2021-01-07 18:53 UTC, AlmasB requested changes

2021-01-07 18:53 UTC, AlmasB commented on fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/components/TransformComponent.kt
Looks good, but please fix spacing. The IDE formatting should be set to *4 spaces, no Tabs*.

2021-01-07 18:53 UTC, AlmasB commented on fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/components/TransformComponent.kt
Same comment as above

2021-01-07 18:53 UTC, AlmasB commented on fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/components/ViewComponent.kt
Same comment

2021-01-09 16:32 UTC, VasilisAndritsoudis commented
@AlmasB I am not sure as to why the formatting was off. I opened the files in two different environments (with tab size set to 4 spaces) and they looked fine. However when uploaded to github there was an error with the spacing. I fixed them through github hoping it will work.

2021-01-09 17:00 UTC, AlmasB approved these changes
Looks good. ViewComponent still had a tab, which I replaced with 4 spaces, but TransformComponent was fine. Thanks.

2021-01-09 17:00 UTC, merged

2021-01-09 17:44 UTC, AlmasB commented
Closes #923