Dublication Fixed in AnimatedValue.kt #925
AlmasB/FXGL pull request #931
Opened 2021-01-08 15:17 UTC by GeorgeJoLo

I have made the changes you suggest me and I also add a test for each class.

2021-01-08 18:09 UTC, AlmasB requested changes
Looks good, please have a look at the comments

2021-01-08 18:09 UTC, AlmasB commented on fxgl-animation/src/main/kotlin/com/almasb/fxgl/animation/AnimatedValue.kt
> +	private val Animated2D = AnimatedQuadBezierPoint2D(path)
Something odd with formatting, please check that spaces are set to 4 and no tabs.

2021-01-08 18:09 UTC, AlmasB commented on fxgl-animation/src/main/kotlin/com/almasb/fxgl/animation/AnimatedValue.kt
> +	private val Animated2D = AnimatedQuadBezierPoint2D(path)
Variable names start with lowercase, so `Animated2D -> animated2D`

2021-01-08 18:09 UTC, AlmasB commented on fxgl-animation/src/main/kotlin/com/almasb/fxgl/animation/AnimatedValue.kt
> +	private val Animated2D = AnimatedCubicBezierPoint2D(path)
Same comments as above, spacing and variable name

2021-01-09 16:27 UTC, GeorgeJoLo commented
I changed everything you mentioned.
I made a commit in my fork, but I didn't submit a new PR, but I believe this is enough.

Waiting for news!

2021-01-09 17:05 UTC, AlmasB commented
Please check the CI output, copied for convenience:

```
Error:  Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile (compile) on project fxgl-animation: Compilation failure: Compilation failure: 
Error:  /home/runner/work/FXGL/FXGL/fxgl-animation/src/main/kotlin/com/almasb/fxgl/animation/AnimatedValue.kt:[111,17] Unresolved reference: Animated2D
Error:  /home/runner/work/FXGL/FXGL/fxgl-animation/src/main/kotlin/com/almasb/fxgl/animation/AnimatedValue.kt:[123,17] Unresolved reference: Animated2D
```

2021-01-09 17:32 UTC, GeorgeJoLo commented
I corrected them!

2021-01-09 17:42 UTC, AlmasB approved these changes
Looks good, thanks!

2021-01-09 17:43 UTC, merged

2021-01-09 17:43 UTC, GeorgeJoLo commented
Your welcome!

2021-01-09 17:43 UTC, AlmasB commented
Closes #925